### ISSUE TITLE
Reference doc not being linted in YAML

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rsconnect#282]
When I publish a PowerPoint presentation with a template, the linter does not pick up the file by default. I would expect to see `template.potx` in the publish dialog.

```
---
title: "Templates"
output:
  powerpoint_presentation:
    reference_doc: template.potx
---

### Overview
```

![image](https://user-images.githubusercontent.com/7519295/42110998-f6970402-7bb0-11e8-9b9f-534427e0ec4a.png)
